# Generated by Django 5.1 on 2024-11-13 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('relations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='condomanager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='condoowner',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='places.condominium'),
        ),
        migrations.AddField(
            model_name='condoowner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='condotenant',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='places.apartment'),
        ),
        migrations.AddField(
            model_name='condotenant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
