# Generated by Django 5.1 on 2024-12-11 11:27

import django.db.models.deletion
from django.db import migrations, models

import relations.models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("relations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                validators=[relations.models.contract_relation_validator],
            ),
        ),
    ]
