# Generated by Django 5.1 on 2024-12-26 14:47

import django.db.models.deletion
import relations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("places", "0001_initial"),
        ("relations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="condostaff",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="condotenant",
            name="apartment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="places.apartment"
            ),
        ),
        migrations.AddField(
            model_name="condotenant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                validators=[relations.models.contract_relation_validator],
            ),
        ),
    ]
