# Generated by Django 5.1 on 2024-11-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condostaff',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='condostaff',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='condotenant',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='condotenant',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='condostaff',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='condotenant',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contract',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
