# Generated by Django 5.1 on 2025-01-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0003_alter_breachpenalty_contract_and_more"),
        ("condo_files", "0005_rename_contractfiles_condotenantcontractfiles_and_more"),
        ("relations", "0006_remove_contract_content_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contract",
        ),
    ]
