# Generated by Django 5.1 on 2025-01-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0007_delete_contract"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="condotenant",
            name="is_renter",
        ),
    ]
