# Generated by Django 5.1 on 2025-01-30 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0006_alter_condominium_profile_photo"),
        ("relations", "0008_remove_condotenant_is_renter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="condotenant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("apartment", "user"),
                name="unique_active_tenant_per_apartment",
            ),
        ),
    ]
