# Generated by Django 5.1 on 2025-03-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0009_condotenant_unique_active_tenant_per_apartment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
            },
        ),
        migrations.AlterModelOptions(
            name="condostaff",
            options={
                "verbose_name": "Condominium staff",
                "verbose_name_plural": "Condominium staff",
            },
        ),
        migrations.AlterModelOptions(
            name="condotenant",
            options={"verbose_name": "Tenant", "verbose_name_plural": "Tenants"},
        ),
        migrations.AlterModelOptions(
            name="condotenantcontract",
            options={"verbose_name": "Contract", "verbose_name_plural": "Contracts"},
        ),
        migrations.AlterModelOptions(
            name="placereservation",
            options={
                "ordering": ["date", "start_time"],
                "verbose_name": "Space reservation",
                "verbose_name_plural": "Space reservations",
            },
        ),
    ]
