# Generated by Django 5.1 on 2025-03-09 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0009_alter_apartment_complement_and_more"),
        ("relations", "0011_alter_car_created_at_alter_car_history_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="brand",
            field=models.CharField(max_length=30, verbose_name="brand"),
        ),
        migrations.AlterField(
            model_name="car",
            name="color",
            field=models.CharField(max_length=30, verbose_name="color"),
        ),
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.CharField(max_length=30, verbose_name="model"),
        ),
        migrations.AlterField(
            model_name="car",
            name="plate",
            field=models.CharField(max_length=7, verbose_name="plate"),
        ),
        migrations.AlterField(
            model_name="car",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="condostaff",
            name="condominium",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="places.condominium",
                verbose_name="condominium",
            ),
        ),
        migrations.AlterField(
            model_name="condostaff",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="notes"),
        ),
        migrations.AlterField(
            model_name="condostaff",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("manager", "Manager"),
                    ("vigilant", "Vigilant"),
                    ("doorman", "Doorman"),
                    ("caretaker", "Caretaker"),
                    ("cleaner", "Cleaner"),
                ],
                max_length=10,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="condostaff",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="condotenant",
            name="apartment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="places.apartment",
                verbose_name="apartment",
            ),
        ),
        migrations.AlterField(
            model_name="condotenant",
            name="is_first_contact",
            field=models.BooleanField(default=False, verbose_name="is first contact"),
        ),
        migrations.AlterField(
            model_name="condotenant",
            name="is_responsible",
            field=models.BooleanField(default=False, verbose_name="is responsible"),
        ),
        migrations.AlterField(
            model_name="condotenant",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="notes"),
        ),
        migrations.AlterField(
            model_name="condotenant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="condotenantcontract",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="end date"),
        ),
        migrations.AlterField(
            model_name="condotenantcontract",
            name="start_date",
            field=models.DateField(verbose_name="start date"),
        ),
        migrations.AlterField(
            model_name="condotenantcontract",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="relations.condotenant",
                verbose_name="tenant",
            ),
        ),
        migrations.AlterField(
            model_name="condotenantcontract",
            name="terms",
            field=models.TextField(verbose_name="terms"),
        ),
        migrations.AlterField(
            model_name="placereservation",
            name="date",
            field=models.DateField(verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="placereservation",
            name="end_time",
            field=models.TimeField(verbose_name="end time"),
        ),
        migrations.AlterField(
            model_name="placereservation",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="places.sharedplaces",
                verbose_name="place",
            ),
        ),
        migrations.AlterField(
            model_name="placereservation",
            name="start_time",
            field=models.TimeField(verbose_name="start time"),
        ),
        migrations.AlterField(
            model_name="placereservation",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="relations.condotenant",
                verbose_name="tenant",
            ),
        ),
    ]
