# Generated by Django 5.1 on 2025-03-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0012_alter_car_brand_alter_car_color_alter_car_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="is active"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="is deleted"
            ),
        ),
        migrations.AlterField(
            model_name="condostaff",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="condostaff",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="is active"
            ),
        ),
        migrations.AlterField(
            model_name="condostaff",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="is deleted"
            ),
        ),
        migrations.AlterField(
            model_name="condotenant",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="condotenant",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="is active"
            ),
        ),
        migrations.AlterField(
            model_name="condotenant",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="is deleted"
            ),
        ),
        migrations.AlterField(
            model_name="condotenantcontract",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="condotenantcontract",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="is active"
            ),
        ),
        migrations.AlterField(
            model_name="condotenantcontract",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="is deleted"
            ),
        ),
        migrations.AlterField(
            model_name="placereservation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="placereservation",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="is active"
            ),
        ),
        migrations.AlterField(
            model_name="placereservation",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="is deleted"
            ),
        ),
    ]
