# Generated by Django 5.1 on 2025-03-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0013_alter_car_created_at_alter_car_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condostaff",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("manager", "Manager"),
                    ("vigilant", "Vigilant"),
                    ("doorman", "Doorman"),
                    ("caretaker", "Caretaker"),
                    ("cleaner", "Cleaner"),
                ],
                db_index=True,
                max_length=10,
                verbose_name="role",
            ),
        ),
    ]
