# Generated by Django 5.1 on 2025-05-27 12:36

import django.db.models.deletion
import meus_lares.storages
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "places",
            "0010_alter_apartment_created_at_alter_apartment_is_active_and_more",
        ),
        ("relations", "0014_alter_condostaff_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="name")),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        storage=meus_lares.storages.PublicMediaStorage(),
                        upload_to="relation/role/",
                        verbose_name="picture",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="condostaff",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Proprietário"),
                    ("manager", "Gerente"),
                    ("vigilant", "Vigilante"),
                    ("doorman", "Portador"),
                    ("caretaker", "Zelador"),
                    ("cleaner", "Faxineiro"),
                ],
                db_index=True,
                max_length=10,
                verbose_name="role",
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("can_get", models.BooleanField(default=True, verbose_name="can get")),
                (
                    "can_create",
                    models.BooleanField(default=True, verbose_name="can create"),
                ),
                (
                    "can_update",
                    models.BooleanField(default=True, verbose_name="can update"),
                ),
                (
                    "can_delete",
                    models.BooleanField(default=True, verbose_name="can delete"),
                ),
                (
                    "deleteable",
                    models.BooleanField(default=False, verbose_name="deleteable"),
                ),
                ("name", models.CharField(max_length=20, verbose_name="name")),
                (
                    "model_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="model name"
                    ),
                ),
                (
                    "condominium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="permission_tag",
                        to="places.condominium",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="tags",
            field=models.ManyToManyField(to="relations.tag"),
        ),
        migrations.AddField(
            model_name="condostaff",
            name="tags",
            field=models.ManyToManyField(to="relations.tag"),
        ),
        migrations.AddField(
            model_name="condotenant",
            name="tags",
            field=models.ManyToManyField(to="relations.tag"),
        ),
        migrations.AddField(
            model_name="condotenantcontract",
            name="tags",
            field=models.ManyToManyField(to="relations.tag"),
        ),
        migrations.AddField(
            model_name="placereservation",
            name="tags",
            field=models.ManyToManyField(to="relations.tag"),
        ),
    ]
