# Generated by Django 5.1 on 2025-01-02 18:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_usernotification_confirmed_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usernotification",
            unique_together={("user", "notification")},
        ),
    ]
