# Generated by Django 5.1 on 2025-03-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_usernotification_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AlterModelOptions(
            name="usernotification",
            options={
                "verbose_name": "User notification",
                "verbose_name_plural": "User notifications",
            },
        ),
    ]
