# Generated by Django 5.1 on 2025-03-09 17:13

import django.db.models.deletion
from django.db import migrations, models

import meus_lares.storages


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_alter_notification_created_at_and_more"),
        ("places", "0009_alter_apartment_complement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="condominium",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="places.condominium",
                verbose_name="condominium",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="image",
            field=models.ImageField(
                blank=True,
                storage=meus_lares.storages.PublicMediaStorage(),
                upload_to="notifications/images/",
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="schedule",
            field=models.DateTimeField(blank=True, null=True, verbose_name="schedule"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=100, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="url"),
        ),
    ]
