# Generated by Django 5.1 on 2025-03-16 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_alter_notification_condominium_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotification",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="confirmed at"
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="notifications.notification",
                verbose_name="notification",
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
