# Generated by Django 5.1 on 2025-03-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0008_alter_notification_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotification",
            name="only_confirm",
            field=models.BooleanField(default=True, verbose_name="only confirm"),
        ),
    ]
