# Generated by Django 5.1 on 2025-03-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0009_usernotification_only_confirm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usernotification",
            name="only_confirm",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="only confirm"
            ),
        ),
    ]
