# Generated by Django 5.1 on 2025-05-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0010_alter_usernotification_only_confirm"),
        ("relations", "0015_role_alter_condostaff_role_tag_car_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="tags",
            field=models.ManyToManyField(to="relations.tag"),
        ),
    ]
