# Generated by Django 5.1 on 2024-12-26 14:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BreachPenalty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("history", models.JSONField(blank=True, default=list)),
                ("name", models.CharField(max_length=50)),
                ("value", models.FloatField()),
                (
                    "is_percentage",
                    models.BooleanField(
                        default=False,
                        help_text="Multiplicará e somará as recorrências pendentes até fim do contrato pelo valor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Multa de quebra de contrato do morador",
                "verbose_name_plural": "Multas de quebra de contrato do morador",
            },
        ),
        migrations.CreateModel(
            name="FinePenalty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("history", models.JSONField(blank=True, default=list)),
                ("name", models.CharField(max_length=50)),
                ("value", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("disputed", "Disputed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "infraction_type",
                    models.CharField(
                        choices=[
                            ("delay_payment", "Delay in payment"),
                            ("noise", "Excessive Noise"),
                            ("illegal_parking", "Illegal Parking"),
                            ("safety_violation", "Safety Violation"),
                            ("trash", "Improper Disposal of Trash"),
                            ("break_rules", "General Rule Violation"),
                            ("damaged", "Damaged infrastructure"),
                            ("others", "Others"),
                        ],
                        default="break_rules",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Multa do condomínio",
                "verbose_name_plural": "Multas do condomínio",
            },
        ),
        migrations.CreateModel(
            name="RecurringFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("history", models.JSONField(blank=True, default=list)),
                ("name", models.CharField(max_length=50)),
                (
                    "break_penalizable",
                    models.BooleanField(
                        default=False,
                        help_text="Será considerado no cálculo de multa de quebra de contrato",
                    ),
                ),
                (
                    "delay_penalizable",
                    models.BooleanField(
                        default=False, help_text="Fará uma multa de atraso de pagamento"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("paid_delay", "Paid with delay"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=10,
                    ),
                ),
                ("value", models.FloatField()),
                ("opening_day", models.DateField()),
                ("due_date", models.DateField()),
            ],
            options={
                "verbose_name": "Recorrência de pagamento",
                "verbose_name_plural": "Recorrências de pagamento",
            },
        ),
    ]
