# Generated by Django 5.1 on 2025-01-28 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0002_initial"),
        ("relations", "0006_remove_contract_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breachpenalty",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="relations.condotenantcontract",
            ),
        ),
        migrations.AlterField(
            model_name="breachpenalty",
            name="is_percentage",
            field=models.BooleanField(
                default=False,
                help_text="Multiplicará e somará as recorrências pendentes",
            ),
        ),
        migrations.AlterField(
            model_name="finepenalty",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="relations.condotenantcontract",
            ),
        ),
        migrations.AlterField(
            model_name="recurringfee",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="relations.condotenantcontract",
            ),
        ),
    ]
