# Generated by Django 5.1 on 2025-03-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0003_alter_breachpenalty_contract_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="breachpenalty",
            options={
                "verbose_name": "Resident's breach of contract fine",
                "verbose_name_plural": "Resident's contract breach fines",
            },
        ),
        migrations.AlterModelOptions(
            name="finepenalty",
            options={
                "verbose_name": "Condominium fine",
                "verbose_name_plural": "Condominium fines",
            },
        ),
        migrations.AlterModelOptions(
            name="recurringfee",
            options={
                "verbose_name": "Payment recurrence",
                "verbose_name_plural": "Payment recurrences",
            },
        ),
        migrations.AlterField(
            model_name="breachpenalty",
            name="is_percentage",
            field=models.BooleanField(
                default=False,
                help_text="It will multiply and add the pending recurrences",
            ),
        ),
        migrations.AlterField(
            model_name="recurringfee",
            name="break_penalizable",
            field=models.BooleanField(
                default=False,
                help_text="It will be considered in the calculation of the fine for breach of contract",
            ),
        ),
        migrations.AlterField(
            model_name="recurringfee",
            name="delay_penalizable",
            field=models.BooleanField(
                default=False, help_text="Will charge a late payment fine"
            ),
        ),
    ]
