# Generated by Django 5.1 on 2025-03-09 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0005_alter_breachpenalty_created_at_and_more"),
        ("relations", "0012_alter_car_brand_alter_car_color_alter_car_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breachpenalty",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="relations.condotenantcontract",
                verbose_name="contract",
            ),
        ),
        migrations.AlterField(
            model_name="breachpenalty",
            name="is_percentage",
            field=models.BooleanField(
                default=False,
                help_text="It will multiply and add the pending recurrences",
                verbose_name="is percentage",
            ),
        ),
        migrations.AlterField(
            model_name="breachpenalty",
            name="name",
            field=models.CharField(max_length=50, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="breachpenalty",
            name="value",
            field=models.FloatField(verbose_name="value"),
        ),
        migrations.AlterField(
            model_name="finepenalty",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="relations.condotenantcontract",
                verbose_name="contract",
            ),
        ),
        migrations.AlterField(
            model_name="finepenalty",
            name="description",
            field=models.TextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="finepenalty",
            name="infraction_type",
            field=models.CharField(
                choices=[
                    ("delay_payment", "Delay in payment"),
                    ("noise", "Excessive Noise"),
                    ("illegal_parking", "Illegal Parking"),
                    ("safety_violation", "Safety Violation"),
                    ("trash", "Improper Disposal of Trash"),
                    ("break_rules", "General Rule Violation"),
                    ("damaged", "Damaged infrastructure"),
                    ("others", "Others"),
                ],
                default="break_rules",
                max_length=20,
                verbose_name="infraction type",
            ),
        ),
        migrations.AlterField(
            model_name="finepenalty",
            name="name",
            field=models.CharField(max_length=50, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="finepenalty",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("disputed", "Disputed"),
                ],
                default="pending",
                max_length=10,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="finepenalty",
            name="value",
            field=models.FloatField(verbose_name="value"),
        ),
        migrations.AlterField(
            model_name="recurringfee",
            name="break_penalizable",
            field=models.BooleanField(
                default=False,
                help_text="It will be considered in the calculation of the fine for breach of contract",
                verbose_name="break penalizable",
            ),
        ),
        migrations.AlterField(
            model_name="recurringfee",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="relations.condotenantcontract",
                verbose_name="contract",
            ),
        ),
        migrations.AlterField(
            model_name="recurringfee",
            name="delay_penalizable",
            field=models.BooleanField(
                default=False,
                help_text="Will charge a late payment fine",
                verbose_name="delay penalizable",
            ),
        ),
        migrations.AlterField(
            model_name="recurringfee",
            name="due_date",
            field=models.DateField(verbose_name="due date"),
        ),
        migrations.AlterField(
            model_name="recurringfee",
            name="name",
            field=models.CharField(max_length=50, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="recurringfee",
            name="opening_day",
            field=models.DateField(verbose_name="opening day"),
        ),
        migrations.AlterField(
            model_name="recurringfee",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("paid_delay", "Paid with delay"),
                    ("cancelled", "Cancelled"),
                ],
                default="waiting",
                max_length=10,
                verbose_name="payment status",
            ),
        ),
        migrations.AlterField(
            model_name="recurringfee",
            name="value",
            field=models.FloatField(verbose_name="value"),
        ),
    ]
