# Generated by Django 5.1 on 2025-03-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0006_alter_breachpenalty_contract_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breachpenalty",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="breachpenalty",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="is active"
            ),
        ),
        migrations.AlterField(
            model_name="breachpenalty",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="is deleted"
            ),
        ),
        migrations.AlterField(
            model_name="finepenalty",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="finepenalty",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="is active"
            ),
        ),
        migrations.AlterField(
            model_name="finepenalty",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="is deleted"
            ),
        ),
        migrations.AlterField(
            model_name="recurringfee",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="recurringfee",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="is active"
            ),
        ),
        migrations.AlterField(
            model_name="recurringfee",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="is deleted"
            ),
        ),
    ]
