# Generated by Django 5.1 on 2025-05-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0007_alter_breachpenalty_created_at_and_more"),
        ("relations", "0015_role_alter_condostaff_role_tag_car_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="breachpenalty",
            name="tags",
            field=models.ManyToManyField(to="relations.tag"),
        ),
        migrations.AddField(
            model_name="finepenalty",
            name="tags",
            field=models.ManyToManyField(to="relations.tag"),
        ),
        migrations.AddField(
            model_name="recurringfee",
            name="tags",
            field=models.ManyToManyField(to="relations.tag"),
        ),
    ]
