# Generated by Django 5.1 on 2024-12-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_managers_remove_user_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="history",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
