# Generated by Django 5.1 on 2025-01-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_nick_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified_status",
            field=models.CharField(
                choices=[
                    ("verified", "Verified"),
                    ("pending", "Pending"),
                    ("in_progress", "In progress"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
    ]
