# Generated by Django 5.1 on 2024-09-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='/', upload_to='profile_photo/'),
            preserve_default=False,
        ),
    ]
