# Generated by Django 5.1 on 2025-01-31 02:06

import meus_lares.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_verified_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="document_photo",
            new_name="document_back_photo",
        ),
        migrations.RemoveField(
            model_name="user",
            name="identity_photo",
        ),
        migrations.AddField(
            model_name="user",
            name="document_front_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=meus_lares.storages.PrivateMediaStorage(),
                upload_to="users/document_photo/",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="self_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=meus_lares.storages.PrivateMediaStorage(),
                upload_to="users/document_photo/",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="self_with_document_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=meus_lares.storages.PrivateMediaStorage(),
                upload_to="users/document_photo/",
            ),
        ),
    ]
