# Generated by Django 5.1 on 2024-12-11 13:01

import django.utils.timezone
from django.db import migrations, models

import soft_components.managers


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_is_deleted"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", soft_components.managers.SoftUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
