# Generated by Django 5.1 on 2025-03-09 16:14

import meus_lares.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth",
            field=models.DateField(verbose_name="birth"),
        ),
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.CharField(max_length=11, verbose_name="document number"),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="user",
            name="document_back_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=meus_lares.storages.PrivateMediaStorage(),
                upload_to="users/document_photo/",
                verbose_name="back of document photo",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="document_front_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=meus_lares.storages.PrivateMediaStorage(),
                upload_to="users/document_photo/",
                verbose_name="front of document photo",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="e-mail"),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="full name"),
        ),
        migrations.AlterField(
            model_name="user",
            name="history",
            field=models.JSONField(blank=True, default=list, verbose_name="history"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is deleted"),
        ),
        migrations.AlterField(
            model_name="user",
            name="nick",
            field=models.CharField(max_length=25, verbose_name="nick"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=15, verbose_name="phone number"),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=meus_lares.storages.PublicMediaStorage(),
                upload_to="users/profile_photo/",
                verbose_name="profile photo",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="self_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=meus_lares.storages.PrivateMediaStorage(),
                upload_to="users/document_photo/",
                verbose_name="selfie photo",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="self_with_document_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=meus_lares.storages.PrivateMediaStorage(),
                upload_to="users/document_photo/",
                verbose_name="selfie with document photo",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="verified_status",
            field=models.CharField(
                choices=[
                    ("verified", "Verified"),
                    ("pending", "Pending"),
                    ("in_progress", "In progress"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=15,
                verbose_name="verified status",
            ),
        ),
    ]
