# Generated by Django 5.1 on 2025-03-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_birth_alter_user_cpf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="e-mail"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="is deleted"
            ),
        ),
    ]
