# Generated by Django 5.1 on 2024-11-22 00:41

import uuid

from django.db import migrations, models

import meus_lares.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AptInspectImages",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("history", models.JSONField(blank=True, default=list)),
                (
                    "image",
                    models.ImageField(
                        storage=meus_lares.storages.PrivateMediaStorage(),
                        upload_to="relations/tenant/images",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("in", "In"), ("out", "Out"), ("inspect", "Inspect")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem de Inspeção de Apartamento",
                "verbose_name_plural": "Imagens de Inspeção de Apartamentos",
            },
        ),
        migrations.CreateModel(
            name="ContractFiles",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("history", models.JSONField(blank=True, default=list)),
                (
                    "file",
                    models.FileField(
                        storage=meus_lares.storages.PrivateMediaStorage(),
                        upload_to="relations/contracts/files",
                        validators=[meus_lares.storages.validate_file],
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Arquivo de contrato",
                "verbose_name_plural": "Arquivos de contratos",
            },
        ),
    ]
