# Generated by Django 5.1 on 2025-01-02 18:37

import meus_lares.storages
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condo_files", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestFiles",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("history", models.JSONField(blank=True, default=list)),
                (
                    "file",
                    models.FileField(
                        storage=meus_lares.storages.PrivateMediaStorage(),
                        upload_to="requests/files/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arquivo da requisição",
                "verbose_name_plural": "Arquivos das requisições",
            },
        ),
    ]
