# Generated by Django 5.1 on 2025-01-02 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condo_files", "0003_requestfiles"),
        ("condo_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestfiles",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="condo_requests.condorequest",
            ),
        ),
    ]
