# Generated by Django 5.1 on 2025-01-28 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condo_files", "0004_requestfiles_request"),
        ("relations", "0006_remove_contract_content_type_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContractFiles",
            new_name="CondoTenantContractFiles",
        ),
        migrations.AlterField(
            model_name="condotenantcontractfiles",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="relations.condotenantcontract",
            ),
        ),
    ]
