# Generated by Django 5.1 on 2025-03-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("condo_files", "0005_rename_contractfiles_condotenantcontractfiles_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aptinspectimages",
            options={
                "verbose_name": "Apartment Inspection Image",
                "verbose_name_plural": "Apartment Inspection Images",
            },
        ),
        migrations.AlterModelOptions(
            name="condotenantcontractfiles",
            options={
                "verbose_name": "Contract file",
                "verbose_name_plural": "Contract files",
            },
        ),
        migrations.AlterModelOptions(
            name="requestfiles",
            options={
                "verbose_name": "Request file",
                "verbose_name_plural": "Request files",
            },
        ),
    ]
