# Generated by Django 5.1 on 2025-03-09 17:13

import django.db.models.deletion
import meus_lares.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condo_files", "0007_alter_aptinspectimages_created_at_and_more"),
        ("condo_requests", "0005_alter_condorequest_anonymous_and_more"),
        ("relations", "0012_alter_car_brand_alter_car_color_alter_car_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aptinspectimages",
            name="image",
            field=models.ImageField(
                storage=meus_lares.storages.PrivateMediaStorage(),
                upload_to="relations/tenant/images",
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="aptinspectimages",
            name="role",
            field=models.CharField(
                choices=[("in", "In"), ("out", "Out"), ("inspect", "Inspect")],
                max_length=10,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="aptinspectimages",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="relations.condotenant",
                verbose_name="tenant",
            ),
        ),
        migrations.AlterField(
            model_name="condotenantcontractfiles",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="relations.condotenantcontract",
                verbose_name="contract",
            ),
        ),
        migrations.AlterField(
            model_name="condotenantcontractfiles",
            name="file",
            field=models.FileField(
                storage=meus_lares.storages.PrivateMediaStorage(),
                upload_to="relations/contracts/files",
                validators=[meus_lares.storages.validate_file],
                verbose_name="file",
            ),
        ),
        migrations.AlterField(
            model_name="condotenantcontractfiles",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="requestfiles",
            name="file",
            field=models.FileField(
                storage=meus_lares.storages.PrivateMediaStorage(),
                upload_to="requests/files/",
                verbose_name="file",
            ),
        ),
        migrations.AlterField(
            model_name="requestfiles",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="condo_requests.condorequest",
                verbose_name="request",
            ),
        ),
    ]
