# Generated by Django 5.1 on 2025-03-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condo_files", "0008_alter_aptinspectimages_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aptinspectimages",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="aptinspectimages",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="is active"
            ),
        ),
        migrations.AlterField(
            model_name="aptinspectimages",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="is deleted"
            ),
        ),
        migrations.AlterField(
            model_name="condotenantcontractfiles",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="condotenantcontractfiles",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="is active"
            ),
        ),
        migrations.AlterField(
            model_name="condotenantcontractfiles",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="is deleted"
            ),
        ),
        migrations.AlterField(
            model_name="requestfiles",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="requestfiles",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="is active"
            ),
        ),
        migrations.AlterField(
            model_name="requestfiles",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="is deleted"
            ),
        ),
    ]
