# Generated by Django 5.1 on 2025-05-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condo_files", "0009_alter_aptinspectimages_created_at_and_more"),
        ("relations", "0015_role_alter_condostaff_role_tag_car_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aptinspectimages",
            name="tags",
            field=models.ManyToManyField(to="relations.tag"),
        ),
        migrations.AddField(
            model_name="condotenantcontractfiles",
            name="tags",
            field=models.ManyToManyField(to="relations.tag"),
        ),
        migrations.AddField(
            model_name="requestfiles",
            name="tags",
            field=models.ManyToManyField(to="relations.tag"),
        ),
    ]
