# Generated by Django 5.1 on 2024-08-20 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='requests')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('R', 'RECLAMAÇÃO'), ('M', 'MANUTENÇÃO'), ('O', 'OUTROS')], default='O', max_length=1)),
                ('status', models.CharField(choices=[('A', 'ANDAMENTO'), ('C', 'CONCLUIDO'), ('P', 'PENDENTE')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Requisição',
                'verbose_name_plural': 'Requisições',
            },
        ),
    ]
