# Generated by Django 5.1 on 2024-09-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_delete_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
