# Generated by Django 5.1 on 2024-08-14 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('R', 'RECLAMAÇÃO'), ('M', 'MANUTENÇÃO'), ('O', 'OUTROS')], default='O', max_length=255)),
                ('status', models.CharField(choices=[('A', 'ANDAMENTO'), ('C', 'CONCLUIDO'), ('P', 'PENDENTE')], default='P', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_guardian', to='users.users')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_place', to='places.places')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_requester', to='users.users')),
            ],
            options={
                'verbose_name': 'Requisição',
                'verbose_name_plural': 'Requisições',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='requests')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='requests.request')),
            ],
        ),
    ]
