# Generated by Django 5.1 on 2024-08-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('A', 'ANDAMENTO'), ('C', 'CONCLUIDO'), ('P', 'PENDENTE')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('R', 'RECLAMAÇÃO'), ('M', 'MANUTENÇÃO'), ('O', 'OUTROS')], default='O', max_length=1),
        ),
    ]
