# Generated by Django 5.1 on 2024-08-21 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
