# Generated by Django 5.1 on 2024-11-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='condominium',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='condominium',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='apartment',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='condominium',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
