# Generated by Django 5.1 on 2024-12-26 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_parkingspace"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parkingspace",
            options={
                "verbose_name": "Vaga de estacionamento",
                "verbose_name_plural": "Vagas de estacionamento",
            },
        ),
        migrations.AlterField(
            model_name="apartment",
            name="identifier",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="identifier",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
