# Generated by Django 5.1 on 2024-10-03 13:51

import meus_lares.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='profile_photo',
            field=models.ImageField(blank=True, storage=meus_lares.storages.PrivateMediaStorage(), upload_to='places/profile-photo/'),
        ),
    ]
