# Generated by Django 5.1 on 2024-11-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_apartment_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='complement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
