# Generated by Django 5.1 on 2024-09-07 02:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_places_residents_alter_places_unions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='residents',
            field=models.ManyToManyField(blank=True, related_name='place_residents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='places',
            name='unions',
            field=models.ManyToManyField(blank=True, related_name='place_unions', to=settings.AUTH_USER_MODEL),
        ),
    ]
