# Generated by Django 5.1 on 2024-09-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_places_residents_alter_places_unions'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='places/profile-photo/'),
        ),
    ]
