# Generated by Django 5.1 on 2024-11-01 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_state_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='state',
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='place_city', to='places.city'),
        ),
    ]
