# Generated by Django 5.1 on 2024-12-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_remove_parkingspace_user_parkingspace_apartment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharedplaces",
            name="capacity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharedplaces",
            name="clean_time",
            field=models.PositiveIntegerField(
                blank=True, help_text="Tempo para limpeza, em minutos", null=True
            ),
        ),
    ]
