# Generated by Django 5.1 on 2025-01-17 01:00

import meus_lares.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0005_alter_sharedplaces_capacity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condominium",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=meus_lares.storages.PublicMediaStorage(),
                upload_to="places/profile-photo/",
            ),
        ),
    ]
