# Generated by Django 5.1 on 2024-11-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_place_complement_place_neighborhood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='cep',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
