# Generated by Django 5.1 on 2025-03-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0006_alter_condominium_profile_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apartment",
            options={"verbose_name": "Apartment", "verbose_name_plural": "Apartments"},
        ),
        migrations.AlterModelOptions(
            name="condominium",
            options={
                "verbose_name": "Condominium",
                "verbose_name_plural": "Condominiums",
            },
        ),
        migrations.AlterModelOptions(
            name="parkingspace",
            options={
                "verbose_name": "Parking space",
                "verbose_name_plural": "Parking space",
            },
        ),
        migrations.AlterModelOptions(
            name="sharedplaces",
            options={
                "verbose_name": "Shared space",
                "verbose_name_plural": "Shared spaces",
            },
        ),
        migrations.AlterField(
            model_name="sharedplaces",
            name="clean_time",
            field=models.PositiveIntegerField(
                blank=True, help_text="Cleaning time, in minutes", null=True
            ),
        ),
    ]
