# Generated by Django 5.1 on 2025-03-09 17:13

import django.db.models.deletion
from django.db import migrations, models

import meus_lares.storages


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0008_alter_apartment_created_at_alter_apartment_history_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="complement",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="complement"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="condominium",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="places.condominium",
                verbose_name="condominium",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="identifier",
            field=models.CharField(max_length=255, verbose_name="identifier"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                storage=meus_lares.storages.PublicMediaStorage(),
                upload_to="places/profile-photo/",
                verbose_name="profile photo",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=50, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="places.state",
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="condominium",
            name="cep",
            field=models.CharField(max_length=8, verbose_name="cep"),
        ),
        migrations.AlterField(
            model_name="condominium",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="place_city",
                to="places.city",
                verbose_name="city",
            ),
        ),
        migrations.AlterField(
            model_name="condominium",
            name="complement",
            field=models.CharField(
                max_length=255, null=True, verbose_name="complement"
            ),
        ),
        migrations.AlterField(
            model_name="condominium",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="condominium",
            name="neighborhood",
            field=models.CharField(max_length=255, verbose_name="neighborhood"),
        ),
        migrations.AlterField(
            model_name="condominium",
            name="number",
            field=models.CharField(max_length=20, null=True, verbose_name="number"),
        ),
        migrations.AlterField(
            model_name="condominium",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=meus_lares.storages.PublicMediaStorage(),
                upload_to="places/profile-photo/",
                verbose_name="profile photo",
            ),
        ),
        migrations.AlterField(
            model_name="condominium",
            name="street",
            field=models.CharField(max_length=255, verbose_name="street"),
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="apartment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="places.apartment",
                verbose_name="apartment",
            ),
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="complement",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="complement"
            ),
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="condominium",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="places.condominium",
                verbose_name="condominium",
            ),
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="identifier",
            field=models.CharField(max_length=255, verbose_name="identifier"),
        ),
        migrations.AlterField(
            model_name="sharedplaces",
            name="capacity",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="capacity"
            ),
        ),
        migrations.AlterField(
            model_name="sharedplaces",
            name="clean_time",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Cleaning time, in minutes",
                null=True,
                verbose_name="clean time",
            ),
        ),
        migrations.AlterField(
            model_name="sharedplaces",
            name="complement",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="complement"
            ),
        ),
        migrations.AlterField(
            model_name="sharedplaces",
            name="condominium",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="places.condominium",
                verbose_name="condominium",
            ),
        ),
        migrations.AlterField(
            model_name="sharedplaces",
            name="identifier",
            field=models.CharField(max_length=255, verbose_name="identifier"),
        ),
        migrations.AlterField(
            model_name="sharedplaces",
            name="is_reserveable",
            field=models.BooleanField(default=True, verbose_name="is reserveable"),
        ),
        migrations.AlterField(
            model_name="state",
            name="acronym",
            field=models.CharField(
                max_length=2, primary_key=True, serialize=False, verbose_name="acronym"
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="name"),
        ),
    ]
