# Generated by Django 5.1 on 2025-03-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0009_alter_apartment_complement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="is active"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="is deleted"
            ),
        ),
        migrations.AlterField(
            model_name="condominium",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="condominium",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="is active"
            ),
        ),
        migrations.AlterField(
            model_name="condominium",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="is deleted"
            ),
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="is active"
            ),
        ),
        migrations.AlterField(
            model_name="parkingspace",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="is deleted"
            ),
        ),
        migrations.AlterField(
            model_name="sharedplaces",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="sharedplaces",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="is active"
            ),
        ),
        migrations.AlterField(
            model_name="sharedplaces",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="is deleted"
            ),
        ),
    ]
