# Generated by Django 5.1 on 2025-05-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "places",
            "0010_alter_apartment_created_at_alter_apartment_is_active_and_more",
        ),
        ("relations", "0015_role_alter_condostaff_role_tag_car_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="tags",
            field=models.ManyToManyField(to="relations.tag"),
        ),
        migrations.AddField(
            model_name="parkingspace",
            name="tags",
            field=models.ManyToManyField(to="relations.tag"),
        ),
        migrations.AddField(
            model_name="sharedplaces",
            name="tags",
            field=models.ManyToManyField(to="relations.tag"),
        ),
    ]
