# Generated by Django 5.1 on 2025-03-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("condo_requests", "0002_condorequest_anonymous"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="condorequest",
            options={"verbose_name": "Request", "verbose_name_plural": "Requests"},
        ),
    ]
