# Generated by Django 5.1 on 2025-03-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condo_requests", "0003_alter_condorequest_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condorequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="condorequest",
            name="history",
            field=models.JSONField(blank=True, default=list, verbose_name="history"),
        ),
        migrations.AlterField(
            model_name="condorequest",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
        migrations.AlterField(
            model_name="condorequest",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is deleted"),
        ),
    ]
