# Generated by Django 5.1 on 2025-03-09 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condo_requests", "0004_alter_condorequest_created_at_and_more"),
        ("places", "0009_alter_apartment_complement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="condorequest",
            name="anonymous",
            field=models.BooleanField(default=False, verbose_name="anonymous"),
        ),
        migrations.AlterField(
            model_name="condorequest",
            name="apartment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="places.apartment",
                verbose_name="apartment",
            ),
        ),
        migrations.AlterField(
            model_name="condorequest",
            name="condominium",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="places.condominium",
                verbose_name="condominium",
            ),
        ),
        migrations.AlterField(
            model_name="condorequest",
            name="description",
            field=models.TextField(max_length=3000, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="condorequest",
            name="guardian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="request_guardian",
                to=settings.AUTH_USER_MODEL,
                verbose_name="guardian",
            ),
        ),
        migrations.AlterField(
            model_name="condorequest",
            name="observations",
            field=models.JSONField(
                blank=True, default=list, verbose_name="observations"
            ),
        ),
        migrations.AlterField(
            model_name="condorequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="request_requester",
                to=settings.AUTH_USER_MODEL,
                verbose_name="requester",
            ),
        ),
        migrations.AlterField(
            model_name="condorequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                    ("awaiting_payment", "Awaiting Payment"),
                    ("rejected", "Rejected"),
                    ("awaiting_feedback", "Awaiting Feedback"),
                ],
                default="pending",
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="condorequest",
            name="title",
            field=models.CharField(max_length=50, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="condorequest",
            name="type",
            field=models.CharField(
                choices=[
                    ("complaint", "Complaint"),
                    ("repair", "Repair"),
                    ("others", "Others"),
                    ("reservation", "Reservation"),
                    ("payment_issue", "Payment Issue"),
                    ("noise_complaint", "Noise Complaint"),
                    ("security_issue", "Security Issue"),
                    ("lost_found", "Lost and Found"),
                    ("visitor_authorization", "Visitor Authorization"),
                    ("package_delivery", "Package Delivery"),
                    ("suggestion", "Suggestion"),
                    ("event", "Event"),
                    ("billing_question", "Billing Question"),
                    ("vehicle", "Vehicle"),
                ],
                default="others",
                verbose_name="type",
            ),
        ),
    ]
