"""
Django settings for meus_lares project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

import environ
from corsheaders.defaults import default_headers
from google.oauth2 import service_account

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR.parent, ".env"))

IS_DOCKER = env("IS_DOCKER") == "True"

if IS_DOCKER:
    environ.Env.read_env(os.path.join(BASE_DIR, "venv", ".env"))
    DB_HOST = env("DB_HOST_DOCKER")
    DB_PORT = env("DB_PORT_DOCKER")
else:
    DB_HOST = env("DB_HOST")
    DB_PORT = env("DB_PORT")


SECRET_KEY = (env("SECRET_KEY"),)

INSTALLED_APPS = [
    "corsheaders",
    "rest_framework",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "users.apps.UserConfig",
    "places.apps.PlacesConfig",
    "relations.apps.RelationsConfig",
    "condo_files.apps.CondoFilesConfig",
    "bills.apps.BillsConfig",
    "notifications.apps.NotificationsConfig",
    "condo_requests.apps.CondoRequestsConfig",
    "storages",
]

AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]


ROOT_URLCONF = "meus_lares.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "users", "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "meus_lares.wsgi.application"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGE_CODE = "pt-br"

LANGUAGES = [
    ("en", "English"),
    ("pt-br", "Português brasileiro"),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]


TIME_ZONE = "America/Sao_Paulo"

APPEND_SLASH = False

USE_I18N = True

USE_TZ = True

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": DB_HOST,
        "PORT": DB_PORT,
    }
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env("EMAIL_PORT")
EMAIL_USE_TLS = env("EMAIL_USE_TLS") == "True"
EMAIL_USE_SSL = env("EMAIL_USE_SSL") == "True"
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_LOGOUT_ON_GET = True

GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID")
SITE_ID = 1

URL_BACK = env("URL_BACK")
URL_FRONT = env("URL_FRONT")
LOGIN_REDIRECT_URL = URL_FRONT
LOGOUT_REDIRECT_URL = URL_FRONT + "/login"
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = LOGOUT_REDIRECT_URL

STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

DEFAULT_FILE_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
STATICFILES_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"

GS_DEFAULT_ACL = None

ENV = env("ENV")

if ENV == "production":
    DEBUG = False

    ALLOWED_HOSTS = [URL_FRONT.lstrip("https://"), URL_BACK.lstrip("https://")]

    SITE = URL_BACK.lstrip("https://")

    CSRF_TRUSTED_ORIGINS = [
        URL_FRONT,
        URL_BACK,
    ]

    CORS_ALLOWED_ORIGINS = [URL_FRONT, URL_BACK]
    CORS_ORIGIN_WHITELIST = [URL_FRONT, URL_BACK]

    GOOGLE_CLOUD_PROJECT_ID = env("GOOGLE_CLOUD_PROJECT_ID")
    GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
        os.path.join(BASE_DIR, ".gcloud", env("GOOGLE_APPLICATION_CREDENTIALS"))
    )

    GS_BUCKET_MEDIA = env("GS_BUCKET_MEDIA")
    GS_BUCKET_STATIC = env("GS_BUCKET_STATIC")

    GS_STATIC_LOCATION = ""
    STATIC_URL = f"https://storage.googleapis.com/{GS_BUCKET_STATIC}/"

    GS_MEDIA_LOCATION = ""
    MEDIA_URL = f"https://storage.googleapis.com/{GS_BUCKET_MEDIA}/"

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
            "OPTIONS": {
                "bucket_name": GS_BUCKET_MEDIA,
                "credentials": GS_CREDENTIALS,
                "location": GS_MEDIA_LOCATION,
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
            "OPTIONS": {
                "bucket_name": GS_BUCKET_STATIC,
                "credentials": GS_CREDENTIALS,
                "location": GS_STATIC_LOCATION,
            },
        },
    }

    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    MIDDLEWARE.append("meus_lares.middleware.DomainAccessMiddleware")


elif ENV == "storage":

    interface_port = env("INTERFACE_PORT")

    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

    GOOGLE_CLOUD_PROJECT_ID = env("GOOGLE_CLOUD_PROJECT_ID")
    GS_CREDENTIALS = service_account.Credentials.from_service_account_file(
        os.path.join(BASE_DIR, ".gcloud", env("GOOGLE_APPLICATION_CREDENTIALS"))
    )

    GS_BUCKET_MEDIA = env("GS_BUCKET_MEDIA")
    GS_BUCKET_STATIC = env("GS_BUCKET_STATIC")

    GS_STATIC_LOCATION = ""
    STATIC_URL = f"https://storage.googleapis.com/{GS_BUCKET_STATIC}/"

    GS_MEDIA_LOCATION = ""
    MEDIA_URL = f"https://storage.googleapis.com/{GS_BUCKET_MEDIA}/"

    STATIC_URL += "static/"

    DEBUG = True
    SITE = f"localhost:{env('API_PORT')}"
    CSRF_TRUSTED_ORIGINS = [
        f"http://localhost:{interface_port}",
        f"http://127.0.0.1:{interface_port}",
    ]

    CORS_ALLOWED_ORIGINS = [
        f"http://localhost:{interface_port}",
        f"http://127.0.0.1:{interface_port}",
    ]

    CORS_ORIGIN_WHITELIST = [
        f"http://localhost:{interface_port}",
        f"http://127.0.0.1:{interface_port}",
    ]

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
            "OPTIONS": {
                "bucket_name": GS_BUCKET_MEDIA,
                "credentials": GS_CREDENTIALS,
                "location": GS_MEDIA_LOCATION,
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
            "OPTIONS": {
                "bucket_name": GS_BUCKET_STATIC,
                "credentials": GS_CREDENTIALS,
                "location": GS_STATIC_LOCATION,
            },
        },
    }


else:

    interface_port = env("INTERFACE_PORT")

    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

    DEBUG = True
    SITE = f"localhost:{env('API_PORT')}"
    CSRF_TRUSTED_ORIGINS = [
        f"http://localhost:{interface_port}",
        f"http://127.0.0.1:{interface_port}",
    ]

    CORS_ALLOWED_ORIGINS = [
        f"http://localhost:{interface_port}",
        f"http://127.0.0.1:{interface_port}",
    ]

    CORS_ORIGIN_WHITELIST = [
        f"http://localhost:{interface_port}",
        f"http://127.0.0.1:{interface_port}",
    ]

    MEDIA_URL = "/media/"
    STATIC_URL = "static/"

    STATIC_ROOT = os.path.join(BASE_DIR, "static_root")
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
